/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7df728c7-145d-45c4-80b7-b24450e690e6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ECB505jTp",
    "aws_user_pools_web_client_id": "6lgch215mu459kj0tjpfeejjvr",
    "oauth": {}
};


export default awsmobile;
