/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b4166118-3398-4c95-9970-a7967d9ecb45",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qVECbIS7v",
    "aws_user_pools_web_client_id": "3uqr5ag1j4iqijeb2phalrnvce",
    "oauth": {}
};


export default awsmobile;
